#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim: filetype=python
"""rice is a customization manager written in python."""
from ricing.parsers import rice_parser


if __name__ == "__main__":
    parser = rice_parser()
    args = parser.parse_args()
